[[friend]]
name = "StarTrail"
url = "https://startrails.site"
description = "星轨前哨基地"
# src="https://startrails.site/favicon.svg"
avatar = "/static/img/friends/startrail.svg"

[[friend]]
name = "沉渊覆雪 - 繁华不复"
url = "https://0o0.codeberg.page"
description = "愿走向深渊的旅途里可以遇见无限美好"
# src="https://0o0.codeberg.page/img/avatar_hu_d4c2d797ac3a9b7.png
avatar = "/static/img/friends/avatar_chen.webp"

[[friend]]
name = "A Moment's Rest"
url = "https://a-moment096.github.io"
# src="https://a-moment096.github.io/avatar.jpg"
avatar = "/static/img/friends/avatar_a_moment.webp"
description = "AMoment 的 Blog"

[[friend]]
name = "Ling 的小窝"
url = "https://blog.llma.top"
# src="https://blog.llma.top/assets/images/avatar.png"
avatar = "static/img/friends/avatar_ling.webp"
description = "一只Tac"

[[friend]]
name = "CLoverta的博客"
url = "https://blog.cloverta.top"
avatar = "static/img/friends/cloverta.webp"
description = "THINK FAST"

[[friend]]
name = "涵曦猫猫的小窝"
url = "https://next-cat.com"
# src="https://next-cat.com/logo"
avatar = "static/img/friends/next_cat.webp"
description = "一只小猫的小窝"

[[friend]]
name = "CatBox"
url = "https://mahiro.ink"
# src="https://mahiro.ink/upload/image_2025-10-25_22-57-27.png"
avatar = "static/img/friends/cat_box.webp"
description = "绘晴的猫砂盆"

[[friend]]
name = "Remik1r3n Blog"
url = "https://blog.remiki.ren"
# src="https://s2.loli.net/2025/09/19/dJtaOl2fVGKUb8n.jpg"
avatar = "static/img/friends/remi.webp"
description = "Remi 的 Blog"
